ALTER TABLE DEPT ADD LOCATION VARCHAR2(100);

UPDATE DEPT SET LOCATION = (
	SELECT CASE WHEN STATE_PROVINCE IS NULL THEN CITY ELSE CITY||', '||STATE_PROVINCE  END 
	FROM LOCATIONS
	WHERE LOCATION_ID = DEPT.LOCATION_ID
);

SELECT *
	FROM dept;

